apiVersion: v1
kind: Service
metadata:
  name: quantumleap
  namespace: fiware-platform
  labels:
    app: quantumleap
spec:
  ports:
  - port: 8668
    targetPort: 8668
    name: http
  selector:
    app: quantumleap
  type: ClusterIP