apiVersion: v1
kind: Service
metadata:
  name: iot-agent
  namespace: fiware-platform
  labels:
    app: iot-agent
spec:
  ports:
  - port: 4041                         # API Port (North)
    targetPort: 4041
    name: api
  - port: 7896                         # HTTP Port (South)
    targetPort: 7896
    name: http
  selector:
    app: iot-agent
  type: ClusterIP