apiVersion: v1
kind: Service
metadata:
  name: cratedb
  namespace: fiware-platform
  labels:
    app: cratedb
spec:
  ports:
  - port: 4200
    targetPort: 4200
    name: http
  - port: 5432
    targetPort: 5432
    name: postgres
  selector:
    app: cratedb
  type: ClusterIP
