apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  namespace: fiware-platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
      - name: notification-service
        image: smartfarm/notification-service:local
        ports:
        - containerPort: 8000
        env:
        #webhook from .env file
        - name: DISCORD_WEBHOOK_URL
          valueFrom:
            secretKeyRef:
              name: discord-secret
              key: webhook_url_discord
        - name: SEND_DISCORD
          value: "true"
        - name: SEND_EMAIL
          value: "false"
        - name: SEND_SMS
          value: "false"
        