apiVersion: v1
kind: Service
metadata:
  name: influxdb
  namespace: fiware-platform
  labels:
    app: influxdb
spec:
  ports:
  - port: 8086
    targetPort: 8086
    name: http
  selector:
    app: influxdb
  type: ClusterIP